{
    "name": "eCommerce",
    "author": "Business Suite Team",
    "version": "1.0",
    "category": "Website/Website",
    "summary": "Sell your products online",
    "description": "",
    "sequence": 1,
    "depends": [
        "website",
        "sale",
        "website_payment",
        "website_mail",
        "portal_rating",
        "digest"
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/ecommerce.xml",
        "data/data.xml",
        "data/mail_template_data.xml",
        "data/product_snippet_template_data.xml",
        "data/digest_data.xml",
        "views/product_attribute_views.xml",
        "views/product_views.xml",
        "views/account_views.xml",
        "views/onboarding_views.xml",
        "views/sale_report_views.xml",
        "views/sale_order_views.xml",
        "views/crm_team_views.xml",
        "views/templates.xml",
        "views/snippets/snippets.xml",
        "views/snippets/s_dynamic_snippet_products.xml",
        "views/res_config_settings_views.xml",
        "views/digest_views.xml",
        "views/visitor_views.xml",
        "views/base_unit_view.xml"
    ],
    "demo": [
        "data/demo.xml",
    ],
    "installable": True,
    "application": True,
    "post_init_hook": "_post_init_hook",
    "uninstall_hook": "uninstall_hook",
    "assets": {
        "web.assets_frontend": [
            "ecommerce/static/src/scss/ecommerce.scss",
            "ecommerce/static/src/scss/website_mail.scss",
            "ecommerce/static/src/scss/frontend.scss",
            "ecommerce/static/src/js/variant_mixin.js",
            "ecommerce/static/src/js/ecommerce.js",
            "ecommerce/static/src/js/utils.js",
            "ecommerce/static/src/js/payment.js",
            "ecommerce/static/src/js/validate.js",
            "ecommerce/static/src/js/recently_viewed.js",
            "ecommerce/static/src/js/tracking.js",
            "ecommerce/static/src/js/category_link.js",
            "website/static/lib/multirange/multirange_custom.scss",
            "website/static/lib/multirange/multirange_custom.js",
            "sale/static/src/scss/sale_portal.scss",
            "sale/static/src/scss/product_configurator.scss",
            "sale/static/src/js/variant_mixin.js",
        ],
        "web._assets_primary_variables": [
            "ecommerce/static/src/scss/primary_variables.scss",
        ],
        "web.assets_backend": [
            "ecommerce/static/src/js/video_field_preview.js",
            "ecommerce/static/src/js/backend.js",
            "ecommerce/static/src/scss/dashboard.scss",
            "ecommerce/static/src/scss/backend.scss",
            "ecommerce/static/src/js/tours/shop_backend.js",
        ],
        "website.assets_wysiwyg": [
            "ecommerce/static/src/scss/editor.scss",
            "ecommerce/static/src/snippets/s_dynamic_snippet_products/options.js",
        ],
        "website.assets_editor": [
            "ecommerce/static/src/js/editor.js",
            "ecommerce/static/src/js/form_editor.js",
            "ecommerce/static/src/js/tours/shop_frontend.js",
        ],
        "web.assets_common": [
            "ecommerce/static/src/js/tours/tour_utils.js",
            "ecommerce/static/src/js/tours/shop.js",
        ],
        "web.assets_tests": [
            "ecommerce/static/tests/**/*",
        ],
        "web.assets_qweb": [
            "ecommerce/static/src/xml/*.xml",
        ],
    },
    "license": "LGPL-3",
}
